version: '3'

services:
  voting-api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    env_file:
      - .env
  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - type: volume
        source: postgres-db
        target: /var/lib/postgresql/data

volumes:
  postgres-db: